In [1]:
import pandas as pd
import numpy as np

In [2]:
def process_ryanair_data(df):
    
      # Step 1: Filter Ryanair records
    ryanair = df[df["icao_operator"]=="RYR"].copy()
    
    # Step 2: Remove exact duplicates
    ryanair = ryanair.drop_duplicates()

    ryanair = ryanair.drop(columns=["unix_time"], errors="ignore")
    
    # Step 3: Convert date columns
    ryanair["dof"]= pd.to_datetime(ryanair["dof"])
    ryanair["first_seen"]= pd.to_datetime(ryanair["first_seen"])
    ryanair["last_seen"]= pd.to_datetime(ryanair["last_seen"])

    # Step 4: Standardize aircraft models
    aircraft_mapping = {
        "B738": "Boeing 737-800",
        "B38M": "Boeing 737 MAX 8-200",
        "A320": "Airbus A320",
        "B737": "Boeing 737-700"
    }
    ryanair["aircraft_model_clean"]=ryanair["typecode"].map(aircraft_mapping)

    # Step 5: Handle missing aircraft class
    mask = (ryanair["icao_aircraft_class"].isna() & ryanair["typecode"].isin(["B738", "B38M"]))
    ryanair.loc[mask, "icao_aircraft_class"] = "L2J"

    # Step 6: Feature Engineering
    # Extract the weekday name
    ryanair["days_of_the_week"] = ryanair["dof"].dt.day_name()

     # Extract the day of the month
    ryanair["day_of_the_month"] = ryanair["dof"].dt.day

    # Classify records as weekday or weekend
    ryanair["day_type"] = np.where(
        ryanair["days_of_the_week"].isin(["Saturday", "Sunday"]),
        "Weekend",
        "Weekday")
    
     # Create directional route
    ryanair["route"] = ryanair["adep"] + "-" + ryanair["ades"]

     # Create direction-independent airport pair
    def create_airport_pair(row):
        if pd.isna(row["adep"]) or pd.isna(row["ades"]):
            return np.nan

        airports = sorted([row["adep"], row["ades"]])
        return airports[0] + "-" + airports[1]

    ryanair["airport_pair"] = ryanair.apply(
        create_airport_pair, axis=1
    )
    return ryanair

In [3]:
june_df = pd.read_parquet("https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202606.parquet")

In [4]:
june_processed = process_ryanair_data(june_df)
june_processed.shape

(66576, 22)

In [5]:
june_processed[
    ["dof", "days_of_the_week", "day_type",
     "route", "airport_pair", "aircraft_model_clean"]
].head(10)

,dof,days_of_the_week,day_type,route,airport_pair,aircraft_model_clean
11,2026-06-01,Monday,Weekday,NaN,NaN,Boeing 737-800
12,2026-06-01,Monday,Weekday,NaN,NaN,Boeing 737-800
13,2026-06-01,Monday,Weekday,NaN,NaN,Boeing 737-800
36,2026-06-01,Monday,Weekday,NaN,NaN,Boeing 737 MAX 8-200
70,2026-06-01,Monday,Weekday,NaN,NaN,Boeing 737-800
79,2026-06-01,Monday,Weekday,NaN,NaN,Boeing 737 MAX 8-200
81,2026-06-01,Monday,Weekday,NaN,NaN,Boeing 737-800
103,2026-06-01,Monday,Weekday,NaN,NaN,Boeing 737 MAX 8-200
106,2026-06-01,Monday,Weekday,NaN,NaN,Boeing 737 MAX 8-200
139,2026-06-01,Monday,Weekday,NaN,NaN,Boeing 737-800

In [6]:
june_processed["route"].notna().sum()

np.int64(41843)

In [7]:
june_processed["airport_pair"].notna().sum()

np.int64(41843)

In [8]:
# now we test the same pipeline on july dataset

In [9]:
july_df = pd.read_parquet(
    "https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202607.parquet"
)

In [10]:
july_processed = process_ryanair_data(july_df)

july_processed.shape

(70541, 22)

In [11]:
july_processed["route"].notna().sum()

np.int64(46587)

In [12]:
july_processed["airport_pair"].notna().sum()

np.int64(46587)

In [13]:
june_processed["aircraft_model_clean"].isna().sum()

np.int64(0)

In [14]:
july_processed["aircraft_model_clean"].isna().sum()

np.int64(0)

In [15]:
# Step 1: List of months
months = [
    "202507", "202508", "202509",
    "202510", "202511", "202512",
    "202601", "202602", "202603",
    "202604", "202605", "202606",
    "202607"
]

# Step 2: Create an empty list
processed_months = []

# Step 3: Loop through each month
for month in months:

    # Generate the URL for the current month
    url = f"https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_{month}.parquet"

    # Download the raw data
    df = pd.read_parquet(url)

    # Clean the data using our function
    cleaned_df = process_ryanair_data(df)

    # Store the cleaned DataFrame
    processed_months.append(cleaned_df)

    # Display the number of processed records
    print(f"{month}: {len(cleaned_df)} Ryanair records")

202507: 71226 Ryanair records
202508: 67453 Ryanair records
202509: 65810 Ryanair records
202510: 62473 Ryanair records
202511: 42505 Ryanair records
202512: 48698 Ryanair records
202601: 25427 Ryanair records
202602: 42713 Ryanair records
202603: 50919 Ryanair records
202604: 63168 Ryanair records
202605: 63278 Ryanair records
202606: 66576 Ryanair records
202607: 70541 Ryanair records

In [16]:
combined_df = pd.concat(processed_months, ignore_index = True)
combined_df.shape

(740787, 22)

In [17]:
[df.shape for df in processed_months]

[(71226, 22),
 (67453, 22),
 (65810, 22),
 (62473, 22),
 (42505, 22),
 (48698, 22),
 (25427, 22),
 (42713, 22),
 (50919, 22),
 (63168, 22),
 (63278, 22),
 (66576, 22),
 (70541, 22)]

In [18]:
processed_months[0].columns.difference(processed_months[2].columns)

Index([], dtype='object')

In [19]:
combined_df.shape

(740787, 22)

In [20]:
# Next step: Final validation
# Before saving our dataset, let's check whether any aircraft models remain unmapped across the 13 months.

In [21]:
combined_df["aircraft_model_clean"].isna().sum()

np.int64(4)

In [22]:
combined_df.loc[
    combined_df["aircraft_model_clean"].isna(),
    ["typecode", "model", "dof"]
]

       typecode          model        dof
117490     LJ45  Learjet 45 XR 2025-08-05
125440     LJ45  Learjet 45 XR 2025-08-04
274763     LJ45  Learjet 45 XR 2025-11-25
302845     LJ45  Learjet 45 XR 2025-11-25

In [23]:
combined_df["aircraft_model_clean"] = combined_df["aircraft_model_clean"].fillna(
    "Learjet 45 XR"
)

In [24]:
combined_df["aircraft_model_clean"].isna().sum()

np.int64(0)

In [25]:
combined_df.duplicated().sum()

np.int64(0)

In [26]:
combined_df.to_parquet(
    "ryanair_flight_operations_2025_2026.parquet",
    index=False
)

In [28]:
%pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\glen gonsalves\appdata\local\programs\python\python310\lib\site-packages (2.0.48)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: pymysql in c:\users\glen gonsalves\appdata\local\programs\python\python310\lib\site-packages (1.1.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\glen gonsalves\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (4.14.1)
Requirement already satisfied: greenlet>=1 in c:\users\glen gonsalves\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (3.3.2)

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [30]:
from sqlalchemy import create_engine, text
from getpass import getpass
from urllib.parse import quote_plus

password = getpass("root")

engine = create_engine(
    f"mysql+pymysql://root:{quote_plus(password)}@localhost:3306/ryanair_project"
)

root ········

In [31]:
with engine.connect() as connection:
    result = connection.execute(text("SELECT DATABASE();"))
    print(result.scalar())

ryanair_project

In [32]:
# testing the connection before transfering to sql

In [33]:
test_df = combined_df.head(100)

test_df.to_sql(
    name="ryanair_test",
    con=engine,
    if_exists="replace",
    index=False
)

100

In [ ]:
# transfering everything to sql

In [35]:
combined_df.to_sql(
    name="ryanair_flights",
    con=engine,
    if_exists="fail",
    index=False,
    chunksize=5000
)

ValueError: Table 'ryanair_flights' already exists.